### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by shreeramsenthi** [STAT545-UBC-students/hw02-rasiimwe#1]
Hey Rebecca,

This is my peer review for your assignment. First of all, let me start by saying your repository is just *ridiculously* accessible. I think it's awesome that you took the time to talk about the first assignment and how this builds up from there; your use of markdown styling goes way beyond what is expected and really helps make the document more readable; and your comments are neither cryptic nor long winded (which is something I really have not figured out how to do).

As for things to improve upon, I'm really scraping the barrel here, but I am curious as to why you didn't load the `knitr` package so that you could call `kable()` instead of `knitr::kable()`. Another thing I found interesting about your code was your occasional interspersion of base R and tidyverse syntax. Of course, it's not wrong or bad, but it just isn't how I would have approached it.

For example, I would have rewritten:
```{R}
high <- df$pop %>% max
df[df$pop == high,]
```
As:
```{R}
df %>% filter(pop == max(pop))
```

Hope you found that at least a little useful.

Cheers,
Shree

**Comment by rasiimwe** [comment]
@shreeramsenthi 

Hi Shree
Thanks for your kind, helpful and positive criticisms. I have used base R for some months now. I am not surprised it's still in my DNA 😄 but I am loving dplyr and will try to have all my code conform to the syntax of this awesome package. Thanks for the `kable()` hint. I didn't know there was a smarter way of calling it :smile:

Thanks Shree. Have an awesome weekend!

**Comment by shreeramsenthi** [comment]
Thanks! You too! 
And yeah, I just made the switch a few months back. I'm sure you'll be fluent sooner rather than later.
